# -*- coding: iso-8859-1 -*-
################################################################################
#  $Id: SConscript,v 1.1 2005/07/07 14:26:25 jpau Exp $
#  Copyright : UniversitÃƒÂƒÃ‚Â© Paris 12 Val-de-Marne
#              (61 avenue du GÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â©nÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â©ral de Gaulle, 94010, CrÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â©teil, France)
#  Author : Johann DrÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â©o <nojhan@gmail.com>
################################################################################

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with this program; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307 USA

Import('env')

random = ['itsRandom.cpp']

dependencies = ["../../common/random.cpp","../../common/string.cpp","../../common/itsPoint.cpp", \
    "../../problem/itsProblem.cpp","../../communication/itsCommunicationClient.cpp",
    "../itsMetaheuristic.cpp"]

env.StaticLibrary('random',random+dependencies)
