ometah:
	scons
clean:
	scons -c
net:
	scons network=yes
python:
	scons python=yes
pynet:
	scons network=yes python=yes
pynetdbg:
	scons network=yes python=yes debug=yes

eotest:
	cd ./metaheuristic/genetic/ && scons