# -*- coding: iso-8859-1 -*-
################################################################################
#  $Id: SConstruct,v 1.23 2005/11/24 22:25:27 nojhan Exp $
#  Copyright : Free Software Fundation
#  Author : Johann Dréo <nojhan@gmail.com>
################################################################################

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with this program; if not, write to the Free

# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307 USA


################################################################################
# Environment
################################################################################

# flags for optimization, use them in production
foptim = '-fcaller-saves -fcse-follow-jumps -fcse-skip-blocks  \
          -felide-constructors -fexpensive-optimizations -ffast-math \
          -ffloat-store -funroll-all-loops -funroll-loops -O3'

# flags for checking the code
#-Wstrict-prototypes -Wmissing-prototypes 
fcheck = '-Wall -ansi -pedantic -Wimplicit \
          -Wredundant-decls -Wreturn-type -Wunused'
          
# flags for debugging
fdebug = '-ggdb'

# more flags
fsup = '-Wno-deprecated'

# setting the environnement
env = Environment()

# setting the options
opts = Options()
opts.AddOptions( \
    BoolOption('static', 'Build a static version',0), \
    BoolOption('debug', 'Compile with the debug informations',0) \
)
opts.Update(env)

flags=""
if env['debug']==1:
    flags = " ".join( [fcheck,fdebug,fsup] )
else:
    flags = " ".join( [fcheck,fsup] )

env.Replace( CCFLAGS = flags )

Help( \
"""
Usage:
scons [options...] [name=val...] [targets...]

Targets: 
scons ometah: build the main interface
scons example: build a simple example interface
scons install: install the files

Flags:""" + \
  opts.GenerateHelpText(env) + \
"""
Example:
scons ometah static=yes debug=no: build a static version of the main interface, without debugging informations
scons example static=0: build a the shared library and the simple interface dynamically linked
scons -c example: clean the files used to generate the simple interface
scons -c install: uninstall the files
scons -c: clean all the files used for the default build
"""
)

################################################################################
# Source files
################################################################################

# Common
common = ['itsPoint.cpp','geometry.cpp','itsSet.cpp','logic.cpp','matrix.cpp', \
          'random.cpp','string.cpp']
common = [ 'common/'+i for i in common]
          
# Interface
interface = ['itsArgument.cpp']
interface = [ 'interface/'+i for i in interface]

# Problems
problem = ['itsProblem.cpp']
problem = [ 'problem/'+i for i in problem]

cec = ['itsCEC05_SSRPO_Base.cpp', 'itsCEC05_SSRPO_Problems.cpp']
cec = [ 'problem/CEC05/'+i for i in cec]

# Communication
communication = ['itsCommunication.cpp', \
                'itsCommunicationClient.cpp', 'itsCommunicationServer.cpp', \
                'itsCommunicationClient_embedded.cpp', 'itsCommunicationServer_embedded.cpp']
communication = [ 'communication/'+i for i in communication]

# Metaheuristic

metaheuristic = ['itsMetaheuristic.cpp']
metaheuristic = [ 'metaheuristic/'+i for i in metaheuristic]

estimation = ['itsEstimationOfDistribution.cpp','itsHybridEstimationOfDistribution.cpp']
estimation = [ 'metaheuristic/estimation/'+i for i in estimation]

sampling = ['itsGridSampling.cpp']
sampling = [ 'metaheuristic/sampling/'+i for i in sampling]

random = ['itsRandom.cpp']
random = [ 'metaheuristic/random/'+i for i in random]

neldermead = ['itsNelderMead.cpp']
neldermead = [ 'metaheuristic/neldermead/'+i for i in neldermead]

genetic = ['itsJpGenetic.cpp', 'itsSimpleGenetic.cpp']
genetic = [ 'metaheuristic/genetic/'+i for i in genetic]

antcolony = ['itsHybridContinuousInteractingAntColony.cpp']
antcolony = [ 'metaheuristic/antcolony/'+i for i in antcolony]

annealing = ['itsSimulatedAnnealing.cpp']
annealing = [ 'metaheuristic/annealing/'+i for i in annealing]


################################################################################
# Configuration
################################################################################

#conf = Configure(env)
#env = conf.Finish()


################################################################################
# Targets
################################################################################

all = common + communication + metaheuristic + problem + cec + interface \
      + estimation + random + sampling + neldermead + antcolony + genetic + annealing 

if env['static']==1:
    # static library
    Execute(Delete('libometah.so'))
    lib = env.StaticLibrary( target = 'ometah', \
        source = all)
    
    # static interface
    Execute(Delete('ometah'))
    ometah = env.Program( target = 'ometah', source = ['interface/ometah.cpp'], LIBS='ometah', LIBPATH='.' )
        
    # simple example
    Execute(Delete('example'))
    example = env.Program( target = 'example', source = ['interface/example_simple.cpp'], LIBS='ometah', LIBPATH='.' ) 

    # installation
    env.Install('/usr/local/bin', ometah)
    env.Alias('install', '/usr/local/bin')
    
else:
    # shared library
    Execute(Delete('libometah.a'))
    lib = env.SharedLibrary( target = 'ometah', \
        source = all )
        
    # standard interface
    Execute(Delete('ometah'))
    ometah = env.Program( target = 'ometah', source = ['interface/ometah.cpp'], LIBS='ometah', LIBPATH='.') 
    
    # simple example
    Execute(Delete('example'))
    example = env.Program( target = 'example', source = ['interface/example_simple.cpp'], LIBS='ometah', LIBPATH='.') 

    # installation
    env.Install('/usr/lib', lib)
    env.Install('/usr/local/bin', ometah)
    env.Alias('install', '/usr/lib')
    env.Alias('install', '/usr/local/bin')
    
    

Default(ometah)
